/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.HotelManagementSystem;

import com.example.HotelManagementSystem.*;
import java.util.Scanner;

public class App {
   

    public static void main(String[] args) {
        System.out.println("Hello World");
        
        // Using Scanner for Getting Input from User
        Scanner in = new Scanner(System.in);

        String s = in.nextLine();
        System.out.println("You entered string " + s);

        int a = in.nextInt();
        System.out.println("You entered integer " + a);

        float b = in.nextFloat();
        System.out.println("You entered float " + b);
        
        
    }
}
