/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.HotelManagementSystem;

import com.example.HotelManagementSystem.Room.*;
import java.util.LinkedList;
import java.util.Scanner;

public class App {
   
    private static LinkedList<Room> rooms;
    private static LinkedList<Guest> guests;
    private static LinkedList<Employee> employees;
    private static LinkedList<Reservation> reservations;
    
    
    public static void main(String[] args) {
        
        // Novas listas ligadas (de uma unica instância)
        
        rooms = new LinkedList<>();
        guests = new LinkedList<>();
        employees = new LinkedList<>();
        reservations = new LinkedList<>();
        
        int i =0;
        while (i!= 13) {            
            
              
        
        System.out.println("Hello wellcome to the app to manage hotels !");
        
        // Interação com user;
        
        System.out.println("1. Add new room");
        System.out.println("2. Show all rooms");
        System.out.println("3. Edit room");
        System.out.println("4. Add new guest");
        System.out.println("5. Show all guests");
        System.out.println("6. Search guest by name");
        System.out.println("7. Edit guest data");
        System.out.println("8. Create new reservation");
        System.out.println("9. Show all reservations");
        System.out.println("10. Get reservation by guest name");
        System.out.println("11. Get reservation by id");
        System.out.println("12. Edit reservation");
        System.out.println("13. Quit");

Scanner scanner = new Scanner (System.in);

    i = scanner.nextInt();

        switch (i) {
            case 1:
                RoomsController.addNewRoom(rooms, scanner);
                break;
                
            case 2:
                RoomsController.showAllRooms(rooms);                
                break;
                
            case 3:
                RoomsController.editRoom(rooms,scanner);
                break;
                
              
            default:
                throw new AssertionError();
        }

            
            
        }
        
      

    }
}
